 # ----github/workflows/build.yml
name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*'
      - 'release-*'

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          # Go into the single project directory
          Set-Location "$env:GITHUB_WORKSPACE\lyrisyn_plus"
          if (Test-Path .\requirements.txt) {
            pip install -r requirements.txt
          }
          pip install pyinstaller

      - name: PyInstaller build
        run: |
          $Root     = "$env:GITHUB_WORKSPACE"
          $ProjDir  = Join-Path $Root 'lyrisyn_plus'
          $IconPath = Join-Path $ProjDir 'iconLyriSync.ico'
          $Splash   = Join-Path $ProjDir 'splash.png'
          $Readme   = Join-Path $ProjDir 'README.md'
          $Cfg      = Join-Path $ProjDir 'lyrisync_config.yaml'

          Set-Location $ProjDir

          $addDataArgs = @()
          if (Test-Path $Splash) { $addDataArgs += @('--add-data', 'splash.png;.') }

          if (Test-Path $IconPath) {
            pyinstaller --noconfirm --clean `
              --name "LyriSyncPlus" `
              --windowed `
              --icon "$IconPath" `
              --hidden-import websockets `
              --hidden-import aiohttp `
              main.py `
              @addDataArgs
          } else {
            pyinstaller --noconfirm --clean `
              --name "LyriSyncPlus" `
              --windowed `
              --hidden-import websockets `
              --hidden-import aiohttp `
              main.py `
              @addDataArgs
          }

          $DistApp = Join-Path $ProjDir 'dist\LyriSyncPlus'
          if (Test-Path $Readme) { Copy-Item $Readme -Destination $DistApp -Force }
          if (Test-Path $Cfg)    { Copy-Item $Cfg    -Destination $DistApp -Force }
          if (Test-Path $IconPath) { Copy-Item $IconPath -Destination $DistApp -Force }

          if (-not (Test-Path (Join-Path $DistApp 'LyriSyncPlus.exe'))) {
            Write-Error "LyriSyncPlus.exe not found in $DistApp"
            exit 1
          }

      - name: Install NSIS & Inno Setup
        run: |
          choco install nsis innosetup -y
          $nsisPath = "${env:ProgramFiles(x86)}\NSIS\makensis.exe"
          $isccPath = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
          if (-not (Test-Path $nsisPath)) { throw "NSIS not found at $nsisPath" }
          if (-not (Test-Path $isccPath)) { throw "Inno Setup not found at $isccPath" }

      - name: Build NSIS installer
        run: |
          $Root     = "$env:GITHUB_WORKSPACE"
          $ProjDir  = Join-Path $Root 'lyrisyn_plus'
          $DistApp  = Join-Path $ProjDir 'dist\LyriSyncPlus'
          $OutDir   = Join-Path $ProjDir 'dist\installer'
          New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

          $nsis = "${env:ProgramFiles(x86)}\NSIS\makensis.exe"

          # Use tag/branch name as version label
          $ver = "${{ github.ref_name }}"
          if (-not $ver) { $ver = "main" }

          # NSIS script lives INSIDE lyrisyn_plus
          $nsiScript = Join-Path $ProjDir 'LyriSyncPlus.nsi'
          if (-not (Test-Path $nsiScript)) {
            throw "NSIS script not found at $nsiScript"
          }

          # Pass variables via /D; do NOT predefine inside the .nsi
          & $nsis `
            "/DSourceDir=$DistApp" `
            "/DAPP_VERSION=$ver" `
            "/DOutputDir=$OutDir" `
            "$nsiScript"

          if ($LASTEXITCODE -ne 0) { throw "NSIS failed with exit code $LASTEXITCODE" }

      - name: Build Inno Setup installer
        run: |
          $Root     = "$env:GITHUB_WORKSPACE"
          $ProjDir  = Join-Path $Root 'lyrisyn_plus'
          $DistApp  = Join-Path $ProjDir 'dist\LyriSyncPlus'
          $iscc     = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"

          $ver = "${{ github.ref_name }}"
          if (-not $ver) { $ver = "main" }

          # Inno script lives INSIDE lyrisyn_plus
          $issScript = Join-Path $ProjDir 'installer_inno.iss'
          if (-not (Test-Path $issScript)) {
            throw "Inno Setup script not found at $issScript"
          }

          # Provide SourceDir and version as defines
          & $iscc "/DSourceDir=$DistApp" "/DMyAppVersion=$ver" "$issScript"

          if ($LASTEXITCODE -ne 0) { throw "Inno Setup failed with exit code $LASTEXITCODE" }

      - name: Upload PyInstaller app (dist/LyriSyncPlus)
        uses: actions/upload-artifact@v4
        with:
          name: LyriSyncPlus-dist
          path: lyrisyn_plus/dist/LyriSyncPlus

      - name: Upload installers
        uses: actions/upload-artifact@v4
        with:
          name: LyriSyncPlus-installers
          path: |
            lyrisyn_plus/dist/installer/*.exe
            lyrisyn_plus/dist/*.exe
